import {MS} from "../../../../common/magicStrings.mjs"

export const SHORT2LONG = new Map()

SHORT2LONG.set(MS.TXT_BY_LBL_SHORT_CNAT, MS.TXT_BY_LBL_CNAT)
SHORT2LONG.set(MS.TXT_BY_LBL_SHORT_CEU, MS.TXT_BY_LBL_CEU)
SHORT2LONG.set(MS.TXT_BY_LBL_SHORT_CNEU, MS.TXT_BY_LBL_CNEU)
SHORT2LONG.set(MS.TXT_BY_LBL_SHORT_BNAT, MS.TXT_BY_LBL_BNAT)
SHORT2LONG.set(MS.TXT_BY_LBL_SHORT_BEU, MS.TXT_BY_LBL_BEU)
SHORT2LONG.set(MS.TXT_BY_LBL_SHORT_BNEU, MS.TXT_BY_LBL_BNEU)

SHORT2LONG.set(MS.NEU_P_HHAB, MS.TXT_BY_LBL_CNEU)
SHORT2LONG.set(MS.EU_P_HHAB, MS.TXT_BY_LBL_CEU)

SHORT2LONG.set(MS.TOTAL, MS.TXT_BY_LBL_CNEU)