
codeList:
  native: &native
    label: "native"
    code: NAT
  eu: &eu
    label: "EU"
    code: EU_27_2020_FOR
  nonEu: &nonEu
    label: "Non EU"
    code: NEU_27_2020_FOR
  men: &men
    label: "Men"
    code: "M"
  women: &women
    label: "Women"
    code: "W"
  total: &total
    label: "Total"
    code: "T"
  15-74: &15-74
    label: "15 to 74 years"
    code: "Y15-64"              # correct one doesn't exist yet
  20-64: &20-64
    label: "20 to 64 years"
    code: "Y20-24"              # correct one doesn't exist yet
  15-29: &15-29
    label: "15 to 29 years"
    code: "Y25-59"              # correct one doesn't exist yet
  freq: &freq
    label: "Time frequency Annual"
    code: "A"
  unit: &unit
    label: ""
    code: "PC"
  timeStart: &timeStart
    label: "start time"
    code: "2020"
  timeEnd: &timeEnd
    label: "end time"
    code: "2022"
  countries: &countries   #ISO 3166-1 alpha2
    - code: EU
      label: European Union
    - code: EU
      label: EU
    - code: EA
      label: EA
    - code: AT
      label: Austria
    - code: BE
      label: Belgium
    - code: BG
      label: Bulgaria
    - code: CH
      label: Switzerland
    - code: CY
      label: Cyprus
    - code: CZ
      label: Czechia
    - code: DE
      label: Germany
    - code: DK
      label: Denmark
    - code: EE
      label: Estonia
    - code: EL
      label: Greece
    - code: ES
      label: Spain
    - code: FI
      label: Finland
    - code: FR
      label: France
    - code: HR
      label: Croatia
    - code: HU
      label: Hungary
    - code: IE
      label: Ireland
    - code: IS
      label: Iceland
    - code: IT
      label: Italy
    - code: LI
      label: Liechtenstein
    - code: LT
      label: Lithuania
    - code: LU
      label: Luxembourg
    - code: LV
      label: Latvia
    - code: MT
      label: Malta
    - code: NL
      label: Netherlands
    - code: NO
      label: Norway
    - code: PL
      label: Poland
    - code: PT
      label: Portugal
    - code: RO
      label: Romania
    - code: SE
      label: Sweden
    - code: SI
      label: Slovenia
    - code: SK
      label: Slovakia
    - code: UK
      label: United Kingdom


globals:
  baseURL: https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/
  ui:
    dropdown:
      geo: *countries


# these are used as a base for each indicator in the indicators section
indicatorBase:
  dimensions:
    ui:               # UI elements reflect user selection for these
      dropdown:
        - sex:
          - *total
          - *women
          - *men
        - age:
          - *15-74
          - *20-64
          - *15-29
      range:
        - time:
          start: *timeStart
          end: *timeEnd
          # "singles:" could have precedence before start/end (not implemented)
          singles: [1907, 1914, 1938]
      combi:
        - bySelect:
          - c_birth:
              entries:
              - *native
              - *eu
              - *nonEu
              datasetIndex: 0   # ref to indicators.datasets[]
          - citizen:
              entries:
              - *native
              - *eu
              - *nonEu
              datasetIndex: 1
    nonUi:          # request relevant dimensions not represented by an ui element
      freq:
      - *freq
      unit:
      - *unit


# each indicator can overwrite the properties it "inherited" (via merge) from indicatorBase
indicators:

  - name: Migrant population share
    category: Demography
    isInOverview: true
    articleLink: https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Migration_and_migrant_population_statistics
    datasets:
      - id: MIGR_POP3CTB
        source: https://ec.europa.eu/eurostat/databrowser/bookmark/fb8d22a0-054b-4423-a3f9-ec79ee84c87a?lang=en
      - id: MIGR_POP1CTZ
        source: https://ec.europa.eu/eurostat/databrowser/bookmark/d30004bd-976c-40fe-bc40-e9a33abf1fc4?lang=en
    dimensions:
      ui:
        dropdown:
          - age:
            - *15-74
            - label: "0 to 15 years"
              code: "!DOESNTEXIST YET 4!"
            - *15-29
            - *20-64
            - label: "over 65 years"
              code: "!DOESNTEXIST YET 5!"
      nonUi:
        unit:
        - label: "Number"
          code: "NR"

  - name: Employment rate
    category: Employment
    isInOverview: true
    articleLink: https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Migrant_integration_statistics_%E2%80%93_labour_market_indicators
    datasets:
      - id: LFSA_ERGACOB
        source: https://ec.europa.eu/eurostat/databrowser/bookmark/d642741b-30e8-45d3-b160-2abb17d8a2c9?lang=en
      - id: LFSA_ERGAN
        source: https://ec.europa.eu/eurostat/databrowser/bookmark/1a912262-da95-49ac-a154-44479a7dae31?lang=en
    dimensions:
      ui:
        dropdown:
          - sex:
            - *total
            - label: "two"
              code: "two"

  - name: Share of adults at risk of poverty or social exclusion
    category: Social inclusion
    isInOverview: true
    articleLink: https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Migrant_integration_statistics_-_at_risk_of_poverty_and_social_exclusion
    datasets:
      - id: ILC_PEPS06N
        source: https://ec.europa.eu/eurostat/databrowser/bookmark/7acca101-803d-44f2-85cd-834dbe582384?lang=en
      - id: ILC_PEPS05N
        source: https://ec.europa.eu/eurostat/databrowser/bookmark/e5355ba1-b4bf-4f2c-a5d6-4ca46cd88406?lang=en
