# yaml schema for migration dashboard v0.3.0

codeList:

  nativeB: &nativeB
    label: "Native-born"
    code: BNAT    #NAT
  euB: &euB
    label: "Born in another EU country"
    code: BEU     #EU27_2020_FOR
  nonEuB: &nonEuB
    label: "Born in a non-EU country"
    code: BNEU    #NEU27_2020_FOR

  nativeC: &nativeC
    label: "Nationals"
    code: CNAT    #NAT
    selected: true
  euC: &euC
    label: "Citizens of another EU country"
    code: CEU     #EU27_2020_FOR
    selected: true
  nonEuC: &nonEuC
    label: "Citizens of a non-EU country"
    code: CNEU    #NEU27_2020_FOR
    selected: true

  bySelectGroupTitles: &bySelectGroupTitles
    CNAT: By country of citizenship
    BNAT: By country of birth

  men: &men
    label: "Men"
    code: "M"
  women: &women
    label: "Women"
    code: "W"
  total: &total
    label: "Total"
    code: "T"
  15-74: &15-74
    label: "15 to 74 years"
    code: "Y15-64"
  20-64: &20-64
    label: "20 to 64 years"
    code: "Y20-24"
  15-29: &15-29
    label: "15 to 29 years"
    code: "Y25-59"
  18-54: &18-54
    label: "18 to 54 years"
    code: "Y18-54"
  freq: &freq
    label: "Time frequency Annual"
    code: "A"
  unit: &unit
    label: "% of Something"
    code: "PC"
  timeStart: &timeStart
    label: "start time"
    code: "2020"
  timeEnd: &timeEnd
    label: "end time"
    code: "2022"
  countries: &countries   #ISO 3166-1 alpha2
    - code: EU
      label: European Union
    - code: AT
      label: Austria
    - code: BE
      label: Belgium
    - code: BG
      label: Bulgaria
    - code: HR
      label: Croatia
    - code: CY
      label: Cyprus
    - code: CZ
      label: Czechia
    - code: DK
      label: Denmark
    - code: EE
      label: Estonia
    - code: FI
      label: Finland
    - code: FR
      label: France
    - code: DE
      label: Germany
    - code: EL
      label: Greece
    - code: HU
      label: Hungary
    - code: IE
      label: Ireland
    - code: IT
      label: Italy
    - code: LV
      label: Latvia
    - code: LT
      label: Lithuania
    - code: LU
      label: Luxembourg
    - code: MT
      label: Malta
    - code: NL
      label: Netherlands
    - code: PL
      label: Poland
    - code: PT
      label: Portugal
    - code: RO
      label: Romania
    - code: SK
      label: Slovakia
    - code: SI
      label: Slovenia
    - code: ES
      label: Spain
    - code: SE
      label: Sweden
    - code: IS
      label: Iceland
    - code: NO
      label: Norway
    - code: CH
      label: Switzerland
  countryGroups: [AT, IS]
  tenure1: &tenure1
    label: "Owner"
    code: "OWN"
  tenure2: &tenure2
    label: "Tenant"
    code: "RENT"


globals:
  baseURL: https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/
  ui:
    dropdown:
      geo: *countries
  byCitizenGroupTitle: "By country of citizenship"
  byBirthGroupTitle: "By country of birth"


# these are used as a base for each indicator in the indicators section
indicatorBase:
  dimensions:
    ui:               # UI elements reflect user selection for these
      dropdown:
        - Sex:        # in the REST request, this becomes the dimension
            elements:
              - *total    # and code becomes the code; label becomes dropdownbox item
              - *women
              - *men
        - Age:
            elements:
              - *15-74
              - *20-64
              - *15-29
          # note 1: in the implementation, bySelect is treated differently than any other dropdown
          # note 2: must correspond w/ magicStrings.mjs
        - Country of citizenship/birth:
            elements:
              - *nativeC
              - *euC
              - *nonEuC
              - *nativeB
              - *euB
              - *nonEuB
            groups:
              *bySelectGroupTitles
      range:
        - time:
          start: *timeStart
          end: *timeEnd
          # "singles:" could have precedence before start/end (not implemented)
          singles: [1907, 1914, 1938]
    nonUi:          # dimensions which are request-relevant and not represented by an ui element
      freq:
      - *freq
      unit:
      - *unit


# each indicator can overwrite the properties it "inherited" (via merge) from indicatorBase
indicators:

  - name: Migrant population share
    ignore: true
    category: Demography
    isInOverview: true
    articleLink: https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Migration_and_migrant_population_statistics
    datasets:
      citizen:
        id: MIGR_POP1CTZ
        source: https://ec.europa.eu/eurostat/databrowser/bookmark/d30004bd-976c-40fe-bc40-e9a33abf1fc4?lang=en
      birth:
        id: MIGR_POP3CTB
        source: https://ec.europa.eu/eurostat/databrowser/bookmark/fb8d22a0-054b-4423-a3f9-ec79ee84c87a?lang=en
    dimensions:
      ui:
        dropdown:
          - Age:
              elements:
                - *15-74
                - label: "0 to 15 years"
                  code: "!DOESNTEXIST YET 4!"
                - *15-29
                - *20-64
                - label: "over 65 years"
                  code: "!DOESNTEXIST YET 5!"
      nonUi:
        unit:
        - label: "in [Thousends] of Something"
          code: "NR"

  - name: Employment rate
    category: Employment
    isInOverview: true
    articleLink: https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Migrant_integration_statistics_%E2%80%93_labour_market_indicators
    datasets:
      citizen:
        id: LFSA_ERGAN
        source: https://ec.europa.eu/eurostat/databrowser/bookmark/1a912262-da95-49ac-a154-44479a7dae31?lang=en
      birth:
        id: LFSA_ERGACOB
        source: https://ec.europa.eu/eurostat/databrowser/bookmark/d642741b-30e8-45d3-b160-2abb17d8a2c9?lang=en
    dimensions:
      ui:
        dropdown:
          - Sex:
              elements:
                - *total
                - label: "two"
                  code: "two"

  - name: Share of adults at risk of poverty or social exclusion
    ignore: true
    category: Housing
    isInOverview: true
    articleLink: https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Migrant_integration_statistics_-_at_risk_of_poverty_and_social_exclusion
    datasets:
      citizen:
        id: ILC_PEPS05N
        source: https://ec.europa.eu/eurostat/databrowser/bookmark/e5355ba1-b4bf-4f2c-a5d6-4ca46cd88406?lang=en
      birth:
        id: ILC_PEPS06N
        source: https://ec.europa.eu/eurostat/databrowser/bookmark/7acca101-803d-44f2-85cd-834dbe582384?lang=en
    dimensions:
      ui:
        dropdown:
          - Age:
              elements:
                - *20-64

  - name: Home ownership rate
    category: Housing
    isInOverview: true
    articleLink: https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Migrant_integration_statistics_-_housing
    datasets:
      citizen:
        id: ILC_LVPS15
        source: https://ec.europa.eu/eurostat/databrowser/bookmark/cf1f1df3-d356-451d-a0dc-9b38be4cd9c1?lang=en
      birth:
        id: ILC_LVPS16
        source: https://ec.europa.eu/eurostat/databrowser/bookmark/9aa7ad1a-8350-47cd-a9e8-83c8e0c59e23?lang=en
    dimensions:
      ui:
        dropdown:
          - Age:
              elements:
                - *18-54
          - Tenure:
              elements:
                - *tenure1
